# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MovieGrid' do
pod 'AFNetworking', '2.2.1'

end

target 'MovieGridTests' do

end

target 'MovieGridUITests' do

end

